"""OpenDracoCLI 主题系统 (P5)

读 TOML 主题文件 → 生成 textual CSS 字符串 → 运行时切换。

设计要点:
- 不依赖 textual 运行时；本模块只产出 CSS 字符串，由调用方 (DracoApp) 注入 textual App。
- TOML 解析: Python 3.11+ 用标准库 tomllib, 3.10 用 tomli 兜底。
- 纯逻辑、无 IO 副作用 (除读 TOML 文件外)，可独立单测。
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

# 必需的颜色 token (主题 TOML 必须提供全部)
REQUIRED_TOKENS = ("bg", "fg", "accent", "error", "warn", "info", "muted")


@dataclass
class Theme:
    """一个主题的完整定义"""

    name: str                        # 主题名 (如 'draco'/'dark'/'light'/自定义名)
    tokens: dict[str, str]           # 颜色 token: bg/fg/accent/error/warn/info/muted
    terminal_16: dict[str, str]      # 终端 16 色映射 (可选, 可为空 dict)
    css: str = ""                    # 由 tokens 编译生成的 textual CSS


class ThemeError(Exception):
    """主题加载/校验失败"""

    pass


def _load_toml(path: Path) -> dict:
    """读 TOML 文件，Python 3.11+ 用 tomllib，3.10 用 tomli 兜底"""

    try:
        import tomllib  # Python 3.11+ 标准库 (3.10 若装了 backport 也能用)
    except ImportError:
        try:
            import tomli as tomllib  # type: ignore
        except ImportError as e:  # 3.10 且未装 tomli
            raise ThemeError(
                "解析 TOML 需要 Python 3.11+ 的 tomllib 或安装 tomli 包"
            ) from e
    with open(path, "rb") as f:
        return tomllib.load(f)


def _validate_theme_data(
    data: Any, source: str = ""
) -> tuple[str, dict[str, str], dict[str, str]]:
    """校验 TOML 解析后的字典结构

    Returns:
        (name, tokens, terminal_16)
    Raises:
        ThemeError — 缺 name / 缺 [tokens] / 缺必需 token / token 非字符串
    """

    src = f" (来源: {source})" if source else ""
    if not isinstance(data, dict):
        raise ThemeError(f"主题文件根结构必须是表{src}")
    name = data.get("name")
    if not isinstance(name, str) or not name:
        raise ThemeError(f"主题文件缺少有效的 'name' 字段{src}")
    tokens_raw = data.get("tokens")
    if not isinstance(tokens_raw, dict):
        raise ThemeError(f"主题 '{name}' 缺少 [tokens] 表{src}")
    missing = [t for t in REQUIRED_TOKENS if t not in tokens_raw]
    if missing:
        raise ThemeError(
            f"主题 '{name}' 缺少必需 token: {', '.join(missing)}{src}"
        )
    # 规整 token: 必需 token 必须是字符串，原样存入 (hex 或命名色)
    tokens: dict[str, str] = {}
    for t in REQUIRED_TOKENS:
        v = tokens_raw[t]
        if not isinstance(v, str):
            raise ThemeError(f"主题 '{name}' token '{t}' 必须是字符串{src}")
        tokens[t] = v
    # 额外 token 透传 (仅字符串)
    for k, v in tokens_raw.items():
        if k not in tokens and isinstance(v, str):
            tokens[k] = v
    # terminal_16 可选
    term_raw = data.get("terminal_16", {})
    if not isinstance(term_raw, dict):
        raise ThemeError(f"主题 '{name}' [terminal_16] 必须是表{src}")
    terminal_16: dict[str, str] = {}
    for k, v in term_raw.items():
        if isinstance(v, str):
            terminal_16[k] = v
    return name, tokens, terminal_16


def generate_css(
    tokens: dict[str, str], terminal_16: dict[str, str] | None = None
) -> str:
    """从颜色 token 生成 textual CSS 字符串

    生成的 CSS 包含:
    - $background / $color / $accent / $error / $warning / $success / $info / $muted
      等 textual design tokens (覆盖 textual 默认色板)
    - 一个 Screen 级别的基础样式
    - 常用 widget 类样式 (.input-panel/.output-panel/.history-sidebar/.status-bar
      用 accent 边框)
    - 语义色辅助类 (.accent-text / .error-text / .warn-text / .info-text /
      .success-text / .muted-text)
    - 若提供 terminal_16, 额外生成 $term-<color> design tokens

    返回纯文本 CSS 字符串，调用方注入 textual App。
    """

    term = terminal_16 or {}
    bg = tokens["bg"]
    fg = tokens["fg"]
    accent = tokens["accent"]
    error = tokens["error"]
    warn = tokens.get("warn", error)
    info = tokens.get("info", accent)
    muted = tokens.get("muted", fg)

    lines: list[str] = []
    lines.append("/* Auto-generated by opendracocli.tui.theme.generate_css */")
    lines.append("/* 颜色 token 来自主题 TOML，请勿手工编辑此文件 */")
    lines.append("")
    # === textual design tokens (覆盖默认色板) ===
    lines.append(f"$background: {bg};")
    lines.append(f"$color: {fg};")
    lines.append(f"$accent: {accent};")
    lines.append(f"$error: {error};")
    lines.append(f"$warning: {warn};")
    lines.append(f"$success: {info};")
    lines.append(f"$info: {info};")
    lines.append(f"$muted: {muted};")
    # 终端 16 色作为额外 design token ($term-<color>)
    if term:
        lines.append("")
        lines.append("/* 终端 16 色映射 */")
        for k, v in term.items():
            lines.append(f"$term-{k}: {v};")
    lines.append("")
    # === Screen 级基础样式 ===
    lines.append("Screen {")
    lines.append("    background: $background;")
    lines.append("    color: $color;")
    lines.append("}")
    lines.append("")
    # === 常用 widget 类样式 (accent 边框) ===
    lines.append("/* 面板: accent 边框 + 半透明背景 */")
    for cls in (".input-panel", ".output-panel", ".history-sidebar"):
        lines.append(f"{cls} {{")
        lines.append("    border: round $accent;")
        lines.append("    background: $boost;")
        lines.append("    color: $color;")
        lines.append("}")
        lines.append("")
    # 状态栏: 单行更紧凑
    lines.append(".status-bar {")
    lines.append("    border: tall $accent;")
    lines.append("    background: $boost;")
    lines.append("    color: $muted;")
    lines.append("}")
    lines.append("")
    # === 语义色辅助类 ===
    lines.append("/* 语义色辅助类 */")
    lines.append(".accent-text { color: $accent; }")
    lines.append(".error-text { color: $error; }")
    lines.append(".warn-text { color: $warning; }")
    lines.append(".info-text { color: $info; }")
    lines.append(".success-text { color: $success; }")
    lines.append(".muted-text { color: $muted; }")
    lines.append("")
    return "\n".join(lines)


class ThemeProvider:
    """主题加载/切换/注册管理"""

    # 类属性: 指向 opendracocli/tui/styles/themes 目录
    BUILTIN_DIR: Path = Path(__file__).parent / "styles" / "themes"

    def __init__(self) -> None:
        self._themes: dict[str, Theme] = {}      # 已加载主题缓存
        self._custom_dirs: list[Path] = []        # 用户自定义主题目录
        self._current: str = "draco"              # 当前主题名

    @classmethod
    def builtin_themes_dir(cls) -> Path:
        """返回内置主题目录绝对路径: Path(__file__).parent / 'styles' / 'themes'"""

        return cls.BUILTIN_DIR

    def register_custom_dir(self, path: Path) -> None:
        """注册用户自定义主题目录 (启动时扫描)

        重复注册同一目录会被忽略。
        """

        p = Path(path)
        if p not in self._custom_dirs:
            self._custom_dirs.append(p)

    def _find_theme_file(self, name: str) -> Path | None:
        """按 内置目录 → 自定义目录(注册顺序) 查找 <name>.toml"""

        candidates: list[Path] = [self.BUILTIN_DIR / f"{name}.toml"]
        for d in self._custom_dirs:
            candidates.append(d / f"{name}.toml")
        for c in candidates:
            if c.is_file():
                return c
        return None

    def _load_from_file(self, path: Path) -> Theme:
        """从 TOML 文件构造 Theme (校验 + 编译 CSS)"""

        data = _load_toml(path)
        name, tokens, terminal_16 = _validate_theme_data(data, source=str(path))
        css = generate_css(tokens, terminal_16)
        return Theme(
            name=name,
            tokens=tokens,
            terminal_16=terminal_16,
            css=css,
        )

    def load(self, name: str) -> Theme:
        """加载指定主题 (先查缓存, 再查内置目录, 再查自定义目录)。

        不存在抛 ThemeError。加载后编译 CSS 存入 Theme.css。
        """

        # 1. 缓存命中
        cached = self._themes.get(name)
        if cached is not None:
            return cached
        # 2. 文件查找
        path = self._find_theme_file(name)
        if path is None:
            raise ThemeError(f"主题不存在: {name}")
        theme = self._load_from_file(path)
        # 用传入的 name 做缓存键 (便于同名覆盖/别名)
        self._themes[name] = theme
        return theme

    def switch(self, name: str) -> Theme:
        """运行时切换主题: load(name) + 更新 _current + 返回 Theme。

        失败抛 ThemeError, 不改变当前主题。
        """

        theme = self.load(name)  # 可能抛 ThemeError (此时 _current 不变)
        self._current = name
        return theme

    def current(self) -> Theme:
        """返回当前主题 (若未加载则 load(_current))"""

        return self.load(self._current)

    def list_themes(self) -> list[str]:
        """列出所有可用主题名: 内置目录扫描 *.toml + 自定义目录扫描 + 已缓存"""

        names: set[str] = set()
        # 内置目录
        if self.BUILTIN_DIR.is_dir():
            for p in self.BUILTIN_DIR.glob("*.toml"):
                names.add(p.stem)
        # 自定义目录
        for d in self._custom_dirs:
            if d.is_dir():
                for p in d.glob("*.toml"):
                    names.add(p.stem)
        # 已缓存
        names.update(self._themes.keys())
        return sorted(names)
